services:
  localstack:
    image: localstack/localstack:4.3.0
    ports:
      - "4566:4566"
    environment:
      - AWS_DEFAULT_REGION=ap-northeast-1
      - GATEWAY_LISTEN=0.0.0.0:4566
      - SERVICES=lambda,apigateway,iam
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=${DEBUG:-0}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
